version: "3.5"

services:
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    networks:
      - sportal
    ports:
      - 8500:8500
    volumes:
      - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: unless-stopped
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    networks:
      - sportal
    ports:
      - 9998:9998
      - 9999:9999

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    networks:
      - sportal
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - sportal
    volumes:
      - postgres:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - sportal
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - sportal
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - '8086:8086'
    networks:
      - sportal
    volumes:
      - influxdb:/var/lib/influxdb

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    networks:
      - sportal
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  prometheus:
    build: ./prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - sportal
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - sportal
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - sportal
    ports:
      - 5341:80
    volumes:
      - seq:/data

  vault:
    image: vault
    container_name: vault
    restart: unless-stopped
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
    networks:
      - sportal
    ports:
      - 8200:8200

networks:
  sportal:
    name: scholar-portal-network
    external: false

volumes:
  mongo:
  postgres:
  rabbitmq:
  grafana:
  influxdb:
  prometheus:
  consul:
  seq:
  redis: